/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DF;

import com.sun.jmx.snmp.daemon.SnmpInformRequest;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.StyleConstants;

/**
 *
 * @author nur_uddin
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    
    String pathName;
    public int cosineLimit;
    
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectedPath = new javax.swing.JTextField();
        openDirectory = new javax.swing.JButton();
        cosineRadioButton = new javax.swing.JRadioButton();
        md5RadioButton = new javax.swing.JRadioButton();
        crc32RadioButton = new javax.swing.JRadioButton();
        sizeRadioButton = new javax.swing.JRadioButton();
        startFindingButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        progressStatus = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        duplicateShow = new javax.swing.JTextArea();
        cosineLimitTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duplicate_File_Finder_v2.0  by  Nur Uddin sust_cse_2011331025");

        jLabel1.setText("Choose Directory");

        openDirectory.setText("....");
        openDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDirectoryActionPerformed(evt);
            }
        });

        buttonGroup1.add(cosineRadioButton);
        cosineRadioButton.setText("Cosine Similarity");
        cosineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosineRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(md5RadioButton);
        md5RadioButton.setText("MD5");
        md5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md5RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(crc32RadioButton);
        crc32RadioButton.setText("CRC32");
        crc32RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crc32RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(sizeRadioButton);
        sizeRadioButton.setText("File Size");
        sizeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeRadioButtonActionPerformed(evt);
            }
        });

        startFindingButton.setText("Start Finding");
        startFindingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFindingButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Progress Status");

        progressStatus.setColumns(20);
        progressStatus.setRows(5);
        jScrollPane1.setViewportView(progressStatus);

        jLabel3.setText("Duplicate Files");

        duplicateShow.setColumns(20);
        duplicateShow.setRows(5);
        jScrollPane2.setViewportView(duplicateShow);

        cosineLimitTextField.setText("80");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cosineRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cosineLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(md5RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(crc32RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(sizeRadioButton)
                                .addGap(88, 88, 88)
                                .addComponent(startFindingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectedPath, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(openDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cosineRadioButton)
                    .addComponent(md5RadioButton)
                    .addComponent(crc32RadioButton)
                    .addComponent(sizeRadioButton)
                    .addComponent(startFindingButton)
                    .addComponent(cosineLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDirectoryActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChose = new JFileChooser();
        fileChose.setFileSelectionMode(
                JFileChooser.FILES_AND_DIRECTORIES);
        
        int result = fileChose.showOpenDialog(this);
        System.out.println(result);
        
        File fileName = fileChose.getSelectedFile();
        
        if ((fileName == null) || (fileName.getName().equals("")))
        {
            JOptionPane.showMessageDialog(this, "Invalid Name",
                    "Invalid Name", JOptionPane.ERROR_MESSAGE);
            //System.exit(1);
        }
        else{
            pathName = fileName.toString();
        
            selectedPath.setText(pathName);
        }
    }//GEN-LAST:event_openDirectoryActionPerformed

    private void startFindingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFindingButtonActionPerformed
        // TODO add your handling code here:
        if(cosineRadioButton.isSelected()){
            try{
                DFFinder listFiles = new DFFinder(this, pathName, 1);
                String cosineLimit = cosineLimitTextField.getText();
                this.cosineLimit = Integer.parseInt(cosineLimit);
                //listFiles.findDuplicates();
            }catch(Exception e){
                
            }
        }
        else if(md5RadioButton.isSelected()){
            try{
                DFFinder listFiles = new DFFinder(this, pathName, 2);
                
                //listFiles.findDuplicates();
            }catch(Exception e){
                
            }
        }
        else if(crc32RadioButton.isSelected()){
            try{
                DFFinder listFiles = new DFFinder(this, pathName, 3);
                
                //listFiles.findDuplicates();
            }catch(Exception e){
                
            }
        }
        else if (sizeRadioButton.isSelected()){
            try{
                DFFinder listFiles = new DFFinder(this, pathName, 4);
                
                //listFiles.findDuplicates();
            }catch(Exception e){
                
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Select a Method" ,
                   "Warning" , JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_startFindingButtonActionPerformed

    private void md5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md5RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_md5RadioButtonActionPerformed

    private void cosineRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosineRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cosineRadioButtonActionPerformed

    private void crc32RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crc32RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crc32RadioButtonActionPerformed

    private void sizeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeRadioButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html NoireLookAndFeel
         */
        try {
            
            //javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                 
            //javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cosineLimitTextField;
    private javax.swing.JRadioButton cosineRadioButton;
    private javax.swing.JRadioButton crc32RadioButton;
    public javax.swing.JTextArea duplicateShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton md5RadioButton;
    private javax.swing.JButton openDirectory;
    public javax.swing.JTextArea progressStatus;
    private javax.swing.JTextField selectedPath;
    private javax.swing.JRadioButton sizeRadioButton;
    private javax.swing.JButton startFindingButton;
    // End of variables declaration//GEN-END:variables
}
